# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    CONFIG_FILE="$(System.DefaultWorkingDirectory)/dist/applet/assets/config.js"
    echo "Replacing configuration in $CONFIG_FILE"
    # Use sed to replace the localhost string with the production URL
    sed -i 's|http://localhost:5000|https://bharathomes-service.azurewebsites.net|g' $CONFIG_FILE
    echo "Replacement complete."
  displayName: 'Replace config.js values'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist/applet'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true



- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure_Connection'
    appType: 'webAppLinux'
    appName: 'bharathomes'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    runtimeStack: 'NODE|22-lts'